version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "lambda-benchmark"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1so3zmviysctu"
s3_prefix = "lambda-benchmark"
region = "ap-south-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
